plugins {
    id 'com.android.application'
}

android {
    namespace 'com.uqrealitylabs.questrelay'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.uqrealitylabs.questrelay'
        minSdk 32
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        debug {
            manifestPlaceholders = [cleartextEnabled: 'true']
        }
        release {
            manifestPlaceholders = [cleartextEnabled: 'false']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:5.5.0'
    testImplementation 'junit:junit:4.13.2'
}
